services:
  - type: web
    name: termin-tool-komplett
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
